import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./layout.module.css";
import Footer from "@/app/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const url = process.env.STRAPI_API_URL + "/menus";
  const strapiToken = process.env.API_TOKEN_STRAPI;
  const res = await fetch(url, {
    method: "GET",
    headers: {
      Authorization: `bearer ${strapiToken}`,
    },
    cache: "no-cache",
  });
  const { data } = await res.json();
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={styles.header}>
          <menu className={styles.menu}>
            {data.map((item: any) => (
              <li key={item.id}>
                <h3>{item.attributes.title}</h3>
              </li>
            ))}
          </menu>
        </header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
